#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

# Run migrations
alembic upgrade head

# Create initial data in DB
pipenv run python /code/api/app/scripts/init_data.py

uvicorn api.main:app --reload --host 0.0.0.0 --port 8000